import OrganizationsPage from './OrganizationsPage';
import { Organization } from './type';

// TODO: Replace mock data with real data from getOrganizations()
// import { getOrganizations } from '@/action/super-admin/orgnizations/organizationsActions';

const mockOrganizations: Organization[] = [
  {
    id: '1',
    name: 'Acme Corporation',
    domain: 'acme.jadarat-lms.com',
    subscriptionPackage: 'Enterprise',
    totalUsers: 180,
    allowedUsers: 250,
    totalCourses: 45,
    allowedCourses: 100,
    totalContentCreators: 8,
    allowedContentCreators: 15,
    subscriptionExpirationDate: new Date('2026-12-31'),
    status: 'Active',
    allowCreateCourses: true,
    allowCreateAICourses: true,
    allowCreateCoursesFromDocuments: true,
    logo_url: 'https://placehold.co/120x40/706efa/white?text=Acme',
  },
  {
    id: '2',
    name: 'TechStart Inc',
    domain: 'techstart.jadarat-lms.com',
    subscriptionPackage: 'Pro',
    totalUsers: 52,
    allowedUsers: 100,
    totalCourses: 18,
    allowedCourses: 50,
    totalContentCreators: 4,
    allowedContentCreators: 5,
    subscriptionExpirationDate: new Date('2026-09-15'),
    status: 'Active',
    allowCreateCourses: true,
    allowCreateAICourses: true,
    allowCreateCoursesFromDocuments: false,
    logo_url: 'https://placehold.co/120x40/22c55e/white?text=TechStart',
  },
  {
    id: '3',
    name: 'Global Education Ltd',
    domain: 'globaledu.jadarat-lms.com',
    subscriptionPackage: 'Enterprise',
    totalUsers: 420,
    allowedUsers: 500,
    totalCourses: 92,
    allowedCourses: 100,
    totalContentCreators: 14,
    allowedContentCreators: 15,
    subscriptionExpirationDate: new Date('2027-03-01'),
    status: 'Active',
    allowCreateCourses: true,
    allowCreateAICourses: true,
    allowCreateCoursesFromDocuments: true,
    logo_url: 'https://placehold.co/120x40/3b82f6/white?text=GlobalEdu',
  },
  {
    id: '4',
    name: 'Noor Academy',
    domain: 'noor.jadarat-lms.com',
    subscriptionPackage: 'Basic',
    totalUsers: 15,
    allowedUsers: 25,
    totalCourses: 6,
    allowedCourses: 10,
    totalContentCreators: 2,
    allowedContentCreators: 3,
    subscriptionExpirationDate: new Date('2025-11-30'),
    status: 'Expired',
    allowCreateCourses: true,
    allowCreateAICourses: false,
    allowCreateCoursesFromDocuments: false,
    logo_url: 'https://placehold.co/120x40/f59e0b/white?text=Noor',
  },
  {
    id: '5',
    name: 'Saudi Training Institute',
    domain: 'sti.jadarat-lms.com',
    subscriptionPackage: 'Pro',
    totalUsers: 88,
    allowedUsers: 100,
    totalCourses: 34,
    allowedCourses: 50,
    totalContentCreators: 5,
    allowedContentCreators: 5,
    subscriptionExpirationDate: new Date('2026-06-30'),
    status: 'Active',
    allowCreateCourses: true,
    allowCreateAICourses: true,
    allowCreateCoursesFromDocuments: true,
    logo_url: 'https://placehold.co/120x40/ef4444/white?text=STI',
  },
  {
    id: '6',
    name: 'Emirates Learning Hub',
    domain: 'elh.jadarat-lms.com',
    subscriptionPackage: 'Enterprise',
    totalUsers: 310,
    allowedUsers: 500,
    totalCourses: 78,
    allowedCourses: 100,
    totalContentCreators: 12,
    allowedContentCreators: 15,
    subscriptionExpirationDate: new Date('2027-01-15'),
    status: 'Active',
    allowCreateCourses: true,
    allowCreateAICourses: true,
    allowCreateCoursesFromDocuments: true,
    logo_url: 'https://placehold.co/120x40/8b5cf6/white?text=ELH',
  },
];

export default async function OrganizationsPageServer() {
  return <OrganizationsPage initialData={mockOrganizations} />;
}
